### ISSUE TITLE
Validation in a functional component (when using React Hooks)

### ISSUE THREAD

**Issue by dmbrooking** [newbreedofgeek/react-stepzilla#155] opened 2019-09-22 00:18 UTC
I'm using hooks so utilizing functional components. I'm trying to figure out how to define the public `isValidated` function needed for validations (I don't think I actually can with a functional component?).

I've defined the function internal to the component, both as `function isValidated()....` and `const isValidated = () =>`... also defined the function outside the component. Nothing is working. I can't not use functional component so really hoping I can get this working with this module.

Can someone help?

**Comment by newbreedofgeek** [comment] 2019-09-22 01:38
Good question @dmbrooking - I've been meaning to get StepZilla working with Function components + Hooks, I believe it should work fine if you are not doing validation via isValidated and just do some component rendering?

Is the issue only when you want to enforce validation with the location isValidated method?

Can you provide me with some quick sample code so I can reproduce this issue and then see if there is a quick solution?

**Comment by dmbrooking** [comment] 2019-09-22 11:23
Sure. This is my component.... it' pretty simple, just a single input that needs to have some value entered in it. I also tried `required` on the `input` but since the stepzilla progress buttons aren't linked to the form itself, that required isn't triggered.

```
const CustomGenresNameStep = () => {
  const { customGenre, setCustomGenre } = useContext(CustomGenreContext);

  const handleChange = (event) => {
    customGenre.name = event.target.value;
    setCustomGenre(customGenre);
  }

  return (
    <>
      <Container>
        <div style={{textAlign: 'center'}}>
          <form>
            <input required className="custom-genre-name" type="text" onChange={handleChange} />
          </form>
        </div>
      </Container>
    </>
  );
}
```

I've tried the following variations:

```
function isValidated() {
  console.log('isValidate called');
  if (customGenre.name) {
    return true;
  }
  
  return false;
}
```
and
```
const isValidated = () => {
  console.log('isValidate called');
  if (customGenre.name) {
    return true;
  }
  
  return false;
}
```

**Comment by dmbrooking** [comment] 2019-09-22 13:38
How would I enforce the validation without using `isValidated`? I'm open to that idea as well, just can't figure out how....

**Comment by zeel** [comment] 2019-10-07 17:58
@dmbrooking @newbreedofgeek You can write like as following.

```
CustomGenresNameStep.prototype.isValidated = () => {
  console.log('isValidate called');
  if (customGenre.name) {
    return true;
  }
  
  return false;
}
```

**Comment by dmbrooking** [comment] 2019-10-08 00:44
@zeel That's not working. Can we re-open this issue?

**Comment by masudiiuc** [comment] 2019-11-07 22:34
I am facing the same issue. `isValidated` method is not get called when you try to submit the form. This is perfectly working fine with `Class component`.  

```javascript
const ChangePassword = (props) => {

  const inputRef = useRef(null);

  const [values, setValues] = useState({
    currentPassword: '',
    newPassword: '',
    confirmPassword: '',
  });

  const onSubmit = () => {
    console.log('I am here', values);
  };

  const onChange = (e) => {
    const fieldName = e.target.name,
          fieldVal = e.target.value;
    setValues({
      ...values,
      [fieldName] : fieldVal,
    });
  };

  const isValidated = () => {
    console.log('I am here', values);

    return false;
  };

    return <div className="wizard-content">
           <Form.Group>
              <Form.Label>Enter Current Password</Form.Label>
              <Form.Col>
                <Form.Control
                    type="password"
                    name="currentPassword"
                    placeholder="Current Password"
                    onChange={onChange}
                    ref={inputRef}
                    value={values.currentPassword}
                />
              </Form.Col>
            </Form.Group>

            <Form.Group>
              <Form.Label>New Password</Form.Label>
              <Form.Col>
                <Form.Control
                    type="password"
                    name="newPassword"
                    placeholder="New Password"
                    onChange={onChange}
                    ref={inputRef}
                    value={values.newPassword}
                />
              </Form.Col>
            </Form.Group>

            <Form.Group>
              <Form.Label>Confirm New Password</Form.Label>
              <Form.Col>
                <Form.Control
                    type="password"
                    name="confirmPassword"
                    onChange={onChange}
                    placeholder="Confirm New Password"
                    ref={inputRef}
                    value={values.confirmPassword}
                />
              </Form.Col>
            </Form.Group>
</div>
}
```

**Comment by newbreedofgeek** [comment] 2019-11-09 02:06
@masudiiuc @dmbrooking  I'm working on this now

**Comment by newbreedofgeek** [comment] 2019-11-11 00:35
@masudiiuc @dmbrooking @zeel an update on this.

I spent some time looking at this yesterday, unfortunately there is no "easy" fix. I'll give some context so others who come here will know why.

When I first built StepZilla there were only Class Components, when React had "pure, functional components" they built those in a way that they did not have any coupling with the parents components. To provide the easy of use and  "plug and play" experience we have today, StepZilla does validation explicitly by calling `isValidated` on the Step Components, we accomplish this using 'refs' - and refs only work with Class components and as a result Hook based functional components wont work.

Good news is that I worked out to get StepZilla working with Hooks based functional components via Implicit validation, but that will need a new major release which might take me around 3-4 weeks to get to. In the meantime, can you guys use Class Components if you need to enforce isValidated logic?

I'll keep you posted.

**Comment by dmbrooking** [comment] 2019-11-11 00:40
@newbreedofgeek thanks. I had done some digging of my own to see if this was something i could implement and basically came to the same conclusion... just didn’t know if my conclusion was right or not as I’m still figuring hooks out.

For the time being I’ve implemented something custom but it’s not as featured as what Stepzilla offers - so while I’m good for now I do look forward to when I can switch back to this, even if it’s many weeks away.

**Comment by kedessa** [comment] 2019-11-11 03:55
@newbreedofgeek Are you also able to make the jumpToStep utility available to be imported i.e. `import StepZilla, {jumpToStep} from "react-stepzilla"; `
so that we can use that function in a functional component? I've created custom forward and back buttons to handle the validation, but I'm unable to change steps.

**Comment by newbreedofgeek** [comment] 2019-11-12 05:39
@dmbrooking I am close to resolving this - I'll keep you posted.

@wevvin jumpToStep WILL WORK in functional components, as seen in this example:
https://github.com/newbreedofgeek/react-cra-hooks-stepzilla/blob/master/src/HooksWithValidation.js

Let me know if you have any issues

**Comment by wevvin** [comment] 2019-11-12 07:21
@newbreedofgeek Thanks for that! I'm trying to get it to work so that I can have the navigation at the same level as the `<StepZilla>` component, and because it passes the `jumpToStep` function through as a prop, I imagine it's not possible to do this?

`<Fragment>
          <StepZilla steps={steps} endAtStep={7} prevBtnOnLastStep={false} preventEnterSubmission={true}
                     nextTextOnFinalActionStep={"Submit"}
                     nextButtonCls="MuiButtonBase-root MuiButton-root MuiButton-outlined"
                     backButtonCls="MuiButtonBase-root MuiButton-root MuiButton-outlined buttonSpace"/>
          <div className={classes.footerButtons}>
            {currentStep > 0 && currentStep < steps.length &&
                <Button variant="contained" color="primary" onClick={null}>
                    Back
                </Button>
            }
            {currentStep < steps.length - 1 &&
            <Button variant="contained" color="primary" onClick={null}>
                Next
            </Button>
            }
          </div>
          <div style={{clear: 'both'}}/>
      </Fragment>`

Instead, do I need to just define the navigation in each step? Or is there another way that I'm overlooking?

**Comment by wevvin** [comment] 2019-11-14 01:53
@newbreedofgeek Nevermind, I managed to get it all working. 👍

**Comment by zeel** [comment] 2019-11-14 09:07
@wevvin I don't think you can change steps outside of stepzilla. But if you found out can you share it here?

**Comment by keplerk** [comment] 2019-11-19 21:47
Not sure if this could helps, but what i did its query for next button inside my functional component and apply a logic in order to determine if i manually disable it or not.

Dirty fix, but it works.

Regards.

**Comment by AbhaysinghBhosale** [comment] 2020-11-03 14:51
@newbreedofgeek is there any update on this. still i am not able to get it working with functional component where last step i used class component and it works there

**Comment by newbreedofgeek** [comment] 2020-11-04 21:23
@AbhaysinghBhosale sorry, still working on getting validation to work on hooks component - unfortunately no ETA yet, glad you have a workaround in the meantime

**Comment by arslan-egenienext** [comment] 2021-02-02 12:26
@newbreedofgeek any update on validation for functional components with react hooks

**Comment by Zipikinho** [comment] 2021-02-04 17:52
> @AbhaysinghBhosale sorry, still working on getting validation to work on hooks component - unfortunately no ETA yet, glad you have a workaround in the meantime

@newbreedofgeek, any update on this? I have to use function component unfortunately :/

**Comment by KausDobs** [comment] 2021-04-12 04:55
> @AbhaysinghBhosale sorry, still working on getting validation to work on hooks component - unfortunately no ETA yet, glad you have a workaround in the meantime

Any update on Function based component? hope you have done it!

**Comment by newbreedofgeek** [comment] 2021-06-27 05:07
Finally got this all working in a branch I am about to commit to! After this is merged and tested StepZilla's isValidated feature will work with both Class components and Hooks based Function components. Stay tuned...

**Closed** 2021-06-27 10:39 UTC
Labels: Bug, Working On Now

**Comment by newbreedofgeek** [comment] 2021-06-27 10:54
Everyone - this is now done and dusted. StepZilla v7.0.0 will now work with Hooks components (with support for validation as well)

**Comment by seanhermans** [comment] 2023-06-30 05:33
Greetings,

**Comment by seanhermans** [comment] 2023-06-30 05:37
Greetings,
Anyone who has a working example of Hooks components and actually gets the validation working, I will appreciate if you may share it please.

Have been struggling with this for the past day now.

The steps render and everything else works great but I still get an error on the step I have switched validation on.

"Cannot read properties of undefined (reading 'component')
TypeError: Cannot read properties of undefined (reading 'component')
    at stepMoveAllowed (http://localhost:3000/static/js/bundle.js:219170:51)"

![image](https://github.com/newbreedofgeek/react-stepzilla/assets/62391328/50884ee4-8aa0-48c7-a22d-2c706ce02c97)

I will appreciate any assistance.

Thank you.
