### ISSUE TITLE
startAtStep does not work

### ISSUE THREAD

**Issue by stanleycyang** [newbreedofgeek/react-stepzilla#30] opened 2017-04-05 23:19 UTC
It always starts at step 1 (index 0) regardless of the number that is plugged into `startAtStep`,

**Comment by newbreedofgeek** [comment] 2017-04-06 01:01
@stanleycyang I've confirmed that this works fine in 4.4.4

Update the example code as below and it starts at Step 3.

```
render() {
    const steps =
    [
      {name: 'Step1', component: <Step1 getStore={() => (this.getStore())} updateStore={(u) => {this.updateStore(u)}} />},
      {name: 'Step2', component: <Step2 getStore={() => (this.getStore())} updateStore={(u) => {this.updateStore(u)}} />},
      {name: 'Step3', component: <Step3 getStore={() => (this.getStore())} updateStore={(u) => {this.updateStore(u)}} />},
      {name: 'step4', component: <Step4 getStore={() => (this.getStore())} updateStore={(u) => {this.updateStore(u)}} />},
      {name: 'Step5', component: <Step5 getStore={() => (this.getStore())} updateStore={(u) => {this.updateStore(u)}} />},
      {name: 'Step6', component: <Step6 getStore={() => (this.getStore())} updateStore={(u) => {this.updateStore(u)}} />}
    ]

    return (
      <div className='example'>
        <div className='step-progress'>
          <StepZilla
            steps={steps}
            preventEnterSubmission={true}
            nextTextOnFinalActionStep={"Save"}
            hocValidationAppliedTo={[3]}
            startAtStep={2}
           />
        </div>
      </div>
    )
  }
```

**Comment by newbreedofgeek** [comment] 2017-04-17 23:41
Closing as no feedback was received on advice given. Please raise issue again with more details if needed @stanleycyang

**Closed by newbreedofgeek** 2017-04-17 23:41 UTC
Labels: question

**Comment by ajendrex** [comment] 2019-11-06 17:27
Hello, I got into this problem because `startAtStep` value changed after StepZilla's constructor ran. I was able to manage it by using `startAtStep={startStep} key={startStep}` props. Please let me know if you think this solution is fine or if you have a better idea...

Thanks for your work!

**Comment by rasfdeveloper** [comment] 2020-10-08 11:46
> Hello, I got into this problem because `startAtStep` value changed after StepZilla's constructor ran. I was able to manage it by using `startAtStep={startStep} key={startStep}` props. Please let me know if you think this solution is fine or if you have a better idea...
> 
> Thanks for your work!

Can you be more specific about how you solved this problem?
