### ISSUE TITLE
State change problem with nextButtonText

### ISSUE THREAD

**Issue by ghost** [newbreedofgeek/react-stepzilla#116] opened 2018-09-20 12:22 UTC
The problem occurs when the props of the Stepzilla component change due to a state change of the parent component. In this case, the navigation buttons are re-rendered, with the exception of the Next button. Its text is determined by the state of the Stepzilla component.

**Comment by newbreedofgeek** [comment] 2018-10-19 00:09
Sorry @tomtoxx I need more info on this?

How can I repo this? what impact does it have for the end-user that the buttons are re-rendered? is there an actual error?

**Comment by tomtoxx** [comment] 2018-10-19 08:02
If you use i18n, you give the translation function into the step components as props. 

If the user now changes the language, the description of the Back button changes but not the description of the Next button, because it gets its description from the state and not from props.

```
 <button
            style={this.state.showNextBtn ? {} : this.hidden}
            className={props.nextButtonCls}
            onClick={() => {this.next()}}
            id="next-button"
          >
            {this.state.nextStepText}
          </button>
```

The problem is this: ``{this.state.nextStepText}``

**Comment by newbreedofgeek** [comment] 2018-10-23 00:05
I see what you mean now - let me look into it. I'll use your PR as a guide.

**Comment by newbreedofgeek** [comment] 2018-10-23 03:16
@tomtoxx thanks for raising this issue - working on a fix for it made me see that I initially coded a very bad prop->state pattern, where prop changes had to be synced with state which drove the render. This is a very bad design pattern in react.

I have fixed this issue (i have tested it by changing the next / back button text half way through a step process). The fix is in a branch `issue-116`:
https://github.com/newbreedofgeek/react-stepzilla/blob/issue-116/src/main.js#L289
Note: I cleaned up old legacy code as well - the above is just the way I now work with props directly

... Before I raise a PR and bring it into master, can you please check out this branch. Launch in dev-mode:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/README.md#dev

... Update the example implementation 
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Example.js

... With your i18n requirement and verify it all works. 

There is another way to test:
If you are using StepZilla via node_modules (i.e. via npm install). just grab the `src` directly from here https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/main.js as a local copy into your project and import StepZilla from there.

As this is a beaking change and we have many users using this in production I want to make sure its 100% good before merging to master and pushing to NPM.

Again, thanks for your contribution.

**Comment by tomtoxx** [comment] 2018-10-24 13:14
Your changes work great! :smile:

I integrated our i18n workflow into the examples and translated them into German.
The buttons now change the language without any problems!

**Closed as completed** 2018-10-26 00:23 UTC
Labels: Bug
